version: '3'

services:
  # APP  ***************************************************************************************
  node-red-train:
    image: jbjares/node-red-train:train4faircom_v10
    ports:
      - 1880:1880
    command: bash -c "cd /app/train-modelling-tool-gofair/packages/node_modules/node-red && node red.js -s client-installation/settings-cloud41.js"

